# Generated by Django 5.2.7 on 2025-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('weight', 'weight'), ('unit', 'unit')], max_length=100),
        ),
    ]
