# Generated by Django 5.2.7 on 2025-11-12 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Business / Farm name')),
                ('aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('qtl', 'Quintal'), ('ton', 'Ton'), ('pc', 'Piece')], default='kg', max_length=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='farmers.farmerprofile')),
            ],
        ),
    ]
