# Generated by Django 5.2.7 on 2025-11-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='category',
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
