# Generated by Django 5.2.7 on 2025-11-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerUser',
        ),
    ]
