# Generated by Django 5.2.7 on 2025-11-17 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_initial'),
        ('store', '0005_remove_conflictticket_admin_remove_agent_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='farmer_products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_products', to='farmers.farmeraccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_offers', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('farmer', 'product')},
            },
        ),
    ]
